// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcG1m0XILwiE2J23Bvzepx8yHxlecEfys',
    appId: '1:1047897370733:web:059cc2c6eb4ac6b203cf64',
    messagingSenderId: '1047897370733',
    projectId: 'copy-dabdd',
    authDomain: 'copy-dabdd.firebaseapp.com',
    storageBucket: 'copy-dabdd.appspot.com',
    measurementId: 'G-G1YG50DJ1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG-DArlP3RI686noH2K6Xgqym-6AVVK-0',
    appId: '1:1047897370733:android:c2d1d88118418c5203cf64',
    messagingSenderId: '1047897370733',
    projectId: 'copy-dabdd',
    storageBucket: 'copy-dabdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexiTWrB4V_0BU6IkQnGcE9Uq6JZb8vCA',
    appId: '1:1047897370733:ios:60f781888120564603cf64',
    messagingSenderId: '1047897370733',
    projectId: 'copy-dabdd',
    storageBucket: 'copy-dabdd.appspot.com',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexiTWrB4V_0BU6IkQnGcE9Uq6JZb8vCA',
    appId: '1:1047897370733:ios:17f4593d4e9e815703cf64',
    messagingSenderId: '1047897370733',
    projectId: 'copy-dabdd',
    storageBucket: 'copy-dabdd.appspot.com',
    iosBundleId: 'com.example.flutterFb.RunnerTests',
  );
}
