// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZkCsszIHMH65PJ7NVOEPrhKogGXR46U',
    appId: '1:396865649397:web:97fd1ee83b6a5b8a1e63bc',
    messagingSenderId: '396865649397',
    projectId: 'bincher-flutter-project',
    authDomain: 'bincher-flutter-project.firebaseapp.com',
    storageBucket: 'bincher-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJY3gpt0n6VhPo1aq3tmPB4Vfju30dOGQ',
    appId: '1:396865649397:android:6eb943f1a7fc0d351e63bc',
    messagingSenderId: '396865649397',
    projectId: 'bincher-flutter-project',
    storageBucket: 'bincher-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4bxBKum5R2JYFwg382fyiaj0OF-HwPKY',
    appId: '1:396865649397:ios:98712103adb699fd1e63bc',
    messagingSenderId: '396865649397',
    projectId: 'bincher-flutter-project',
    storageBucket: 'bincher-flutter-project.appspot.com',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4bxBKum5R2JYFwg382fyiaj0OF-HwPKY',
    appId: '1:396865649397:ios:68ecdb971e062a721e63bc',
    messagingSenderId: '396865649397',
    projectId: 'bincher-flutter-project',
    storageBucket: 'bincher-flutter-project.appspot.com',
    iosBundleId: 'com.example.flutterFb.RunnerTests',
  );
}